require 'functional/behavior'
require 'functional/concurrency'
require 'functional/obligation'
require 'functional/future'
require 'functional/pattern_matching'
require 'functional/promise'
require 'functional/utilities'
require 'functional/version'
